# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1628, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1611, 821))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ImageWindow = GraphicsLayoutWidget(self.tab)
        self.ImageWindow.setGeometry(QtCore.QRect(30, 30, 512, 512))
        self.ImageWindow.setMouseTracking(True)
        self.ImageWindow.setLineWidth(0)
        self.ImageWindow.setObjectName("ImageWindow")
        self.Prairie_groupBox = QtWidgets.QGroupBox(self.tab)
        self.Prairie_groupBox.setGeometry(QtCore.QRect(560, 20, 331, 111))
        self.Prairie_groupBox.setObjectName("Prairie_groupBox")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.Prairie_groupBox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 311, 81))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.currentZoom_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.currentZoom_comboBox.setObjectName("currentZoom_comboBox")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.currentZoom_comboBox, 2, 1, 1, 1)
        self.pvBufferFrames_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.pvBufferFrames_spinBox.setMinimum(1)
        self.pvBufferFrames_spinBox.setMaximum(30)
        self.pvBufferFrames_spinBox.setProperty("value", 1)
        self.pvBufferFrames_spinBox.setObjectName("pvBufferFrames_spinBox")
        self.gridLayout_5.addWidget(self.pvBufferFrames_spinBox, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.flipRow_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.flipRow_comboBox.setObjectName("flipRow_comboBox")
        self.flipRow_comboBox.addItem("")
        self.flipRow_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.flipRow_comboBox, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.connectPV_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.connectPV_pushButton.setObjectName("connectPV_pushButton")
        self.gridLayout_5.addWidget(self.connectPV_pushButton, 0, 3, 1, 1)
        self.OfflineAnalysis_groupBox = QtWidgets.QGroupBox(self.tab)
        self.OfflineAnalysis_groupBox.setGeometry(QtCore.QRect(900, 420, 331, 81))
        self.OfflineAnalysis_groupBox.setObjectName("OfflineAnalysis_groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.OfflineAnalysis_groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 311, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.moviePath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.moviePath_lineEdit.setObjectName("moviePath_lineEdit")
        self.gridLayout_4.addWidget(self.moviePath_lineEdit, 1, 1, 1, 1)
        self.loadMoviePath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.loadMoviePath_pushButton.setObjectName("loadMoviePath_pushButton")
        self.gridLayout_4.addWidget(self.loadMoviePath_pushButton, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.IsOffline_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.IsOffline_radioButton.setObjectName("IsOffline_radioButton")
        self.gridLayout_4.addWidget(self.IsOffline_radioButton, 0, 0, 1, 1)
        self.DisplayOptions_groupBox = QtWidgets.QGroupBox(self.tab)
        self.DisplayOptions_groupBox.setGeometry(QtCore.QRect(560, 260, 331, 151))
        self.DisplayOptions_groupBox.setObjectName("DisplayOptions_groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.DisplayOptions_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 311, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plotSTAonMasks_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.plotSTAonMasks_pushButton.setObjectName("plotSTAonMasks_pushButton")
        self.gridLayout_7.addWidget(self.plotSTAonMasks_pushButton, 4, 2, 1, 1)
        self.plotSTA_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotSTA_pushButton.sizePolicy().hasHeightForWidth())
        self.plotSTA_pushButton.setSizePolicy(sizePolicy)
        self.plotSTA_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.plotSTA_pushButton.setObjectName("plotSTA_pushButton")
        self.gridLayout_7.addWidget(self.plotSTA_pushButton, 3, 2, 1, 1)
        self.showComponents_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showComponents_pushButton.setObjectName("showComponents_pushButton")
        self.gridLayout_7.addWidget(self.showComponents_pushButton, 0, 2, 1, 1)
        self.denoiseOn_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.denoiseOn_checkBox.setChecked(True)
        self.denoiseOn_checkBox.setObjectName("denoiseOn_checkBox")
        self.gridLayout_7.addWidget(self.denoiseOn_checkBox, 0, 0, 1, 1)
        self.displayOn_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.displayOn_checkBox.setChecked(True)
        self.displayOn_checkBox.setObjectName("displayOn_checkBox")
        self.gridLayout_7.addWidget(self.displayOn_checkBox, 3, 0, 1, 1)
        self.plotOn_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.plotOn_checkBox.setChecked(True)
        self.plotOn_checkBox.setObjectName("plotOn_checkBox")
        self.gridLayout_7.addWidget(self.plotOn_checkBox, 4, 0, 1, 1)
        self.showFOV_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showFOV_pushButton.setObjectName("showFOV_pushButton")
        self.gridLayout_7.addWidget(self.showFOV_pushButton, 0, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.refreshFrame_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.refreshFrame_spinBox.setMinimum(1)
        self.refreshFrame_spinBox.setMaximum(9000)
        self.refreshFrame_spinBox.setProperty("value", 30)
        self.refreshFrame_spinBox.setDisplayIntegerBase(10)
        self.refreshFrame_spinBox.setObjectName("refreshFrame_spinBox")
        self.horizontalLayout.addWidget(self.refreshFrame_spinBox)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_8.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.StimOptions_groupBox = QtWidgets.QGroupBox(self.tab)
        self.StimOptions_groupBox.setGeometry(QtCore.QRect(1240, 20, 341, 171))
        self.StimOptions_groupBox.setObjectName("StimOptions_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.StimOptions_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 11, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 2, 1, 1)
        self.stimStartFrame_spinBox = QtWidgets.QSpinBox(self.StimOptions_groupBox)
        self.stimStartFrame_spinBox.setMinimum(1)
        self.stimStartFrame_spinBox.setMaximum(9000)
        self.stimStartFrame_spinBox.setProperty("value", 238)
        self.stimStartFrame_spinBox.setObjectName("stimStartFrame_spinBox")
        self.gridLayout.addWidget(self.stimStartFrame_spinBox, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.interStimInterval_spinBox = QtWidgets.QSpinBox(self.StimOptions_groupBox)
        self.interStimInterval_spinBox.setMinimum(1)
        self.interStimInterval_spinBox.setMaximum(9000)
        self.interStimInterval_spinBox.setProperty("value", 310)
        self.interStimInterval_spinBox.setObjectName("interStimInterval_spinBox")
        self.gridLayout.addWidget(self.interStimInterval_spinBox, 7, 1, 1, 1)
        self.staPreFrame_spinBox = QtWidgets.QSpinBox(self.StimOptions_groupBox)
        self.staPreFrame_spinBox.setMinimum(1)
        self.staPreFrame_spinBox.setMaximum(900)
        self.staPreFrame_spinBox.setProperty("value", 60)
        self.staPreFrame_spinBox.setObjectName("staPreFrame_spinBox")
        self.gridLayout.addWidget(self.staPreFrame_spinBox, 2, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 8, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.StimOptions_groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 2, 1, 1)
        self.staPostFrame_spinBox = QtWidgets.QSpinBox(self.StimOptions_groupBox)
        self.staPostFrame_spinBox.setMinimum(1)
        self.staPostFrame_spinBox.setMaximum(9000)
        self.staPostFrame_spinBox.setProperty("value", 120)
        self.staPostFrame_spinBox.setObjectName("staPostFrame_spinBox")
        self.gridLayout.addWidget(self.staPostFrame_spinBox, 7, 5, 1, 1)
        self.numberStims_spinBox = QtWidgets.QSpinBox(self.StimOptions_groupBox)
        self.numberStims_spinBox.setMinimum(1)
        self.numberStims_spinBox.setMaximum(500)
        self.numberStims_spinBox.setProperty("value", 15)
        self.numberStims_spinBox.setDisplayIntegerBase(10)
        self.numberStims_spinBox.setObjectName("numberStims_spinBox")
        self.gridLayout.addWidget(self.numberStims_spinBox, 8, 1, 1, 1)
        self.staAvgStartFrame_spinBox = QtWidgets.QSpinBox(self.StimOptions_groupBox)
        self.staAvgStartFrame_spinBox.setMinimum(1)
        self.staAvgStartFrame_spinBox.setMaximum(300)
        self.staAvgStartFrame_spinBox.setProperty("value", 1)
        self.staAvgStartFrame_spinBox.setDisplayIntegerBase(10)
        self.staAvgStartFrame_spinBox.setObjectName("staAvgStartFrame_spinBox")
        self.gridLayout.addWidget(self.staAvgStartFrame_spinBox, 8, 5, 1, 1)
        self.staAvgStopFrame_spinBox = QtWidgets.QSpinBox(self.StimOptions_groupBox)
        self.staAvgStopFrame_spinBox.setMinimum(1)
        self.staAvgStopFrame_spinBox.setMaximum(9000)
        self.staAvgStopFrame_spinBox.setProperty("value", 30)
        self.staAvgStopFrame_spinBox.setDisplayIntegerBase(10)
        self.staAvgStopFrame_spinBox.setObjectName("staAvgStopFrame_spinBox")
        self.gridLayout.addWidget(self.staAvgStopFrame_spinBox, 10, 5, 1, 1)
        self.stimDaqDevice_lineEdit = QtWidgets.QLineEdit(self.StimOptions_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stimDaqDevice_lineEdit.sizePolicy().hasHeightForWidth())
        self.stimDaqDevice_lineEdit.setSizePolicy(sizePolicy)
        self.stimDaqDevice_lineEdit.setMaxLength(500)
        self.stimDaqDevice_lineEdit.setObjectName("stimDaqDevice_lineEdit")
        self.gridLayout.addWidget(self.stimDaqDevice_lineEdit, 11, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 8, 6, 1, 1)
        self.testTTLTrigger_pushButton = QtWidgets.QPushButton(self.StimOptions_groupBox)
        self.testTTLTrigger_pushButton.setObjectName("testTTLTrigger_pushButton")
        self.gridLayout.addWidget(self.testTTLTrigger_pushButton, 11, 5, 1, 1)
        self.enableStimTrigger_checkBox = QtWidgets.QCheckBox(self.StimOptions_groupBox)
        self.enableStimTrigger_checkBox.setObjectName("enableStimTrigger_checkBox")
        self.gridLayout.addWidget(self.enableStimTrigger_checkBox, 11, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.caiman_groupBox = QtWidgets.QGroupBox(self.tab)
        self.caiman_groupBox.setGeometry(QtCore.QRect(900, 140, 331, 271))
        self.caiman_groupBox.setObjectName("caiman_groupBox")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.caiman_groupBox)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(10, 20, 311, 239))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem3, 5, 1, 1, 1)
        self.initialise_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_13)
        self.initialise_pushButton.setObjectName("initialise_pushButton")
        self.gridLayout_19.addWidget(self.initialise_pushButton, 4, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.refMoviePath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.refMoviePath_lineEdit.setObjectName("refMoviePath_lineEdit")
        self.gridLayout_3.addWidget(self.refMoviePath_lineEdit, 0, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.UseOpsinMask_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_13)
        self.UseOpsinMask_radioButton.setEnabled(False)
        self.UseOpsinMask_radioButton.setCheckable(True)
        self.UseOpsinMask_radioButton.setAutoExclusive(False)
        self.UseOpsinMask_radioButton.setObjectName("UseOpsinMask_radioButton")
        self.gridLayout_2.addWidget(self.UseOpsinMask_radioButton, 7, 4, 1, 1)
        self.InitNumROIs_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_13)
        self.InitNumROIs_spinBox.setMinimum(1)
        self.InitNumROIs_spinBox.setProperty("value", 15)
        self.InitNumROIs_spinBox.setObjectName("InitNumROIs_spinBox")
        self.gridLayout_2.addWidget(self.InitNumROIs_spinBox, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.MaxNumROIs_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_13)
        self.MaxNumROIs_spinBox.setMinimum(1)
        self.MaxNumROIs_spinBox.setProperty("value", 40)
        self.MaxNumROIs_spinBox.setObjectName("MaxNumROIs_spinBox")
        self.gridLayout_2.addWidget(self.MaxNumROIs_spinBox, 7, 2, 1, 1)
        self.loadMask_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_13)
        self.loadMask_pushButton.setEnabled(True)
        self.loadMask_pushButton.setIconSize(QtCore.QSize(14, 14))
        self.loadMask_pushButton.setObjectName("loadMask_pushButton")
        self.gridLayout_2.addWidget(self.loadMask_pushButton, 4, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 4, 3, 1, 1)
        self.dsFactor_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_13)
        self.dsFactor_doubleSpinBox.setDecimals(2)
        self.dsFactor_doubleSpinBox.setMinimum(1.0)
        self.dsFactor_doubleSpinBox.setMaximum(15.0)
        self.dsFactor_doubleSpinBox.setProperty("value", 1.5)
        self.dsFactor_doubleSpinBox.setObjectName("dsFactor_doubleSpinBox")
        self.gridLayout_2.addWidget(self.dsFactor_doubleSpinBox, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.UseOnacidMask_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_13)
        self.UseOnacidMask_radioButton.setEnabled(False)
        self.UseOnacidMask_radioButton.setAutoExclusive(False)
        self.UseOnacidMask_radioButton.setObjectName("UseOnacidMask_radioButton")
        self.gridLayout_2.addWidget(self.UseOnacidMask_radioButton, 6, 4, 1, 1)
        self.UseONACID_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_13)
        self.UseONACID_checkBox.setEnabled(True)
        self.UseONACID_checkBox.setChecked(False)
        self.UseONACID_checkBox.setObjectName("UseONACID_checkBox")
        self.gridLayout_2.addWidget(self.UseONACID_checkBox, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 4, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadRefMoviePath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_13)
        self.loadRefMoviePath_pushButton.setObjectName("loadRefMoviePath_pushButton")
        self.horizontalLayout_4.addWidget(self.loadRefMoviePath_pushButton)
        self.takeRefMovie_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_13)
        self.takeRefMovie_pushButton.setObjectName("takeRefMovie_pushButton")
        self.horizontalLayout_4.addWidget(self.takeRefMovie_pushButton)
        self.gridLayout_19.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.plotArea_graphicsLayoutWidget = GraphicsLayoutWidget(self.tab)
        self.plotArea_graphicsLayoutWidget.setGeometry(QtCore.QRect(30, 600, 511, 171))
        self.plotArea_graphicsLayoutWidget.setObjectName("plotArea_graphicsLayoutWidget")
        self.Thresh_tableWidget = QtWidgets.QTableWidget(self.tab)
        self.Thresh_tableWidget.setGeometry(QtCore.QRect(560, 600, 451, 171))
        self.Thresh_tableWidget.setShowGrid(True)
        self.Thresh_tableWidget.setCornerButtonEnabled(False)
        self.Thresh_tableWidget.setObjectName("Thresh_tableWidget")
        self.Thresh_tableWidget.setColumnCount(0)
        self.Thresh_tableWidget.setRowCount(0)
        self.Thresh_tableWidget.horizontalHeader().setVisible(True)
        self.Thresh_tableWidget.horizontalHeader().setHighlightSections(False)
        self.Thresh_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.Blink_groupBox = QtWidgets.QGroupBox(self.tab)
        self.Blink_groupBox.setGeometry(QtCore.QRect(560, 140, 331, 111))
        self.Blink_groupBox.setObjectName("Blink_groupBox")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.Blink_groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 311, 81))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.selectAll_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.selectAll_checkBox.setObjectName("selectAll_checkBox")
        self.gridLayout_6.addWidget(self.selectAll_checkBox, 0, 0, 1, 1)
        self.clearTargets_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.clearTargets_pushButton.setObjectName("clearTargets_pushButton")
        self.gridLayout_6.addWidget(self.clearTargets_pushButton, 1, 0, 1, 1)
        self.connectBlink_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.connectBlink_pushButton.setObjectName("connectBlink_pushButton")
        self.gridLayout_6.addWidget(self.connectBlink_pushButton, 0, 2, 1, 1)
        self.SendCoords_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.SendCoords_pushButton.setObjectName("SendCoords_pushButton")
        self.gridLayout_6.addWidget(self.SendCoords_pushButton, 1, 2, 1, 1)
        self.addNewROIsToTarget_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.addNewROIsToTarget_checkBox.setObjectName("addNewROIsToTarget_checkBox")
        self.gridLayout_6.addWidget(self.addNewROIsToTarget_checkBox, 0, 1, 1, 1)
        self.updateTargets_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.updateTargets_pushButton.setObjectName("updateTargets_pushButton")
        self.gridLayout_6.addWidget(self.updateTargets_pushButton, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 2, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(30, 560, 511, 25))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 6, 1, 1)
        self.CurrentFrameIdx_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.CurrentFrameIdx_label.setObjectName("CurrentFrameIdx_label")
        self.gridLayout_9.addWidget(self.CurrentFrameIdx_label, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 4, 1, 1)
        self.xPos_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.xPos_label.setText("")
        self.xPos_label.setObjectName("xPos_label")
        self.gridLayout_9.addWidget(self.xPos_label, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.yPos_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.yPos_label.setText("")
        self.yPos_label.setObjectName("yPos_label")
        self.gridLayout_9.addWidget(self.yPos_label, 0, 7, 1, 1)
        self.removeMode_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.removeMode_pushButton.setEnabled(True)
        self.removeMode_pushButton.setIconSize(QtCore.QSize(14, 14))
        self.removeMode_pushButton.setObjectName("removeMode_pushButton")
        self.gridLayout_9.addWidget(self.removeMode_pushButton, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(1240, 380, 341, 121))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 321, 91))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 0, 0, 1, 1)
        self.saveResultPath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.saveResultPath_lineEdit.setText("")
        self.saveResultPath_lineEdit.setObjectName("saveResultPath_lineEdit")
        self.gridLayout_13.addWidget(self.saveResultPath_lineEdit, 0, 1, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.browseResultPath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.browseResultPath_pushButton.setObjectName("browseResultPath_pushButton")
        self.horizontalLayout_5.addWidget(self.browseResultPath_pushButton)
        self.getPathFromPV_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.getPathFromPV_pushButton.setObjectName("getPathFromPV_pushButton")
        self.horizontalLayout_5.addWidget(self.getPathFromPV_pushButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.saveResult_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.saveResult_pushButton.setObjectName("saveResult_pushButton")
        self.gridLayout_12.addWidget(self.saveResult_pushButton, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem8, 4, 0, 1, 1)
        self.opsinMask_groupBox = QtWidgets.QGroupBox(self.tab)
        self.opsinMask_groupBox.setGeometry(QtCore.QRect(900, 20, 331, 111))
        self.opsinMask_groupBox.setObjectName("opsinMask_groupBox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.opsinMask_groupBox)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_26 = QtWidgets.QLabel(self.opsinMask_groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout_18.addWidget(self.label_26, 0, 0, 1, 1)
        self.loadOpsinImgPath_pushButton = QtWidgets.QPushButton(self.opsinMask_groupBox)
        self.loadOpsinImgPath_pushButton.setObjectName("loadOpsinImgPath_pushButton")
        self.gridLayout_18.addWidget(self.loadOpsinImgPath_pushButton, 0, 2, 1, 1)
        self.opsinImgPath_lineEdit = QtWidgets.QLineEdit(self.opsinMask_groupBox)
        self.opsinImgPath_lineEdit.setObjectName("opsinImgPath_lineEdit")
        self.gridLayout_18.addWidget(self.opsinImgPath_lineEdit, 0, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.opsinMask_groupBox)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        self.minArea_spinBox = QtWidgets.QSpinBox(self.opsinMask_groupBox)
        self.minArea_spinBox.setMinimum(1)
        self.minArea_spinBox.setMaximum(200)
        self.minArea_spinBox.setSingleStep(10)
        self.minArea_spinBox.setProperty("value", 100)
        self.minArea_spinBox.setObjectName("minArea_spinBox")
        self.horizontalLayout_6.addWidget(self.minArea_spinBox)
        self.label_29 = QtWidgets.QLabel(self.opsinMask_groupBox)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_6.addWidget(self.label_29)
        self.cellRadius_spinBox = QtWidgets.QSpinBox(self.opsinMask_groupBox)
        self.cellRadius_spinBox.setEnabled(True)
        self.cellRadius_spinBox.setAcceptDrops(False)
        self.cellRadius_spinBox.setMinimum(3)
        self.cellRadius_spinBox.setMaximum(19)
        self.cellRadius_spinBox.setSingleStep(2)
        self.cellRadius_spinBox.setProperty("value", 9)
        self.cellRadius_spinBox.setObjectName("cellRadius_spinBox")
        self.horizontalLayout_6.addWidget(self.cellRadius_spinBox)
        self.label_28 = QtWidgets.QLabel(self.opsinMask_groupBox)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.overlapRatio_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.opsinMask_groupBox)
        self.overlapRatio_doubleSpinBox.setDecimals(2)
        self.overlapRatio_doubleSpinBox.setMinimum(0.0)
        self.overlapRatio_doubleSpinBox.setMaximum(1.0)
        self.overlapRatio_doubleSpinBox.setSingleStep(0.1)
        self.overlapRatio_doubleSpinBox.setProperty("value", 0.5)
        self.overlapRatio_doubleSpinBox.setObjectName("overlapRatio_doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.overlapRatio_doubleSpinBox)
        self.gridLayout_15.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.createMask_pushButton = QtWidgets.QPushButton(self.opsinMask_groupBox)
        self.createMask_pushButton.setObjectName("createMask_pushButton")
        self.horizontalLayout_7.addWidget(self.createMask_pushButton)
        self.showCellsOnMask_pushButton = QtWidgets.QPushButton(self.opsinMask_groupBox)
        self.showCellsOnMask_pushButton.setObjectName("showCellsOnMask_pushButton")
        self.horizontalLayout_7.addWidget(self.showCellsOnMask_pushButton)
        self.gridLayout_15.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.config_groupBox = QtWidgets.QGroupBox(self.tab)
        self.config_groupBox.setGeometry(QtCore.QRect(1240, 510, 341, 61))
        self.config_groupBox.setObjectName("config_groupBox")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.config_groupBox)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(10, 20, 321, 31))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.saveConfig_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveConfig_pushButton.sizePolicy().hasHeightForWidth())
        self.saveConfig_pushButton.setSizePolicy(sizePolicy)
        self.saveConfig_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.saveConfig_pushButton.setObjectName("saveConfig_pushButton")
        self.gridLayout_17.addWidget(self.saveConfig_pushButton, 0, 1, 1, 1)
        self.loadConfig_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadConfig_pushButton.sizePolicy().hasHeightForWidth())
        self.loadConfig_pushButton.setSizePolicy(sizePolicy)
        self.loadConfig_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadConfig_pushButton.setObjectName("loadConfig_pushButton")
        self.gridLayout_17.addWidget(self.loadConfig_pushButton, 0, 0, 1, 1)
        self.photostim_groupBox = QtWidgets.QGroupBox(self.tab)
        self.photostim_groupBox.setGeometry(QtCore.QRect(1240, 200, 341, 171))
        self.photostim_groupBox.setObjectName("photostim_groupBox")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.photostim_groupBox)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 321, 142))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.photoPowerPerCell_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.photoPowerPerCell_spinBox.setMaximum(30)
        self.photoPowerPerCell_spinBox.setSingleStep(0)
        self.photoPowerPerCell_spinBox.setProperty("value", 6)
        self.photoPowerPerCell_spinBox.setObjectName("photoPowerPerCell_spinBox")
        self.horizontalLayout_8.addWidget(self.photoPowerPerCell_spinBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_8.addWidget(self.label_31)
        self.gridLayout_11.addLayout(self.horizontalLayout_8, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.photostimDaqDevice_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photostimDaqDevice_lineEdit.sizePolicy().hasHeightForWidth())
        self.photostimDaqDevice_lineEdit.setSizePolicy(sizePolicy)
        self.photostimDaqDevice_lineEdit.setMaxLength(500)
        self.photostimDaqDevice_lineEdit.setObjectName("photostimDaqDevice_lineEdit")
        self.horizontalLayout_3.addWidget(self.photostimDaqDevice_lineEdit)
        self.gridLayout_11.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 2, 0, 1, 1)
        self.photoProto_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_10)
        self.photoProto_comboBox.setObjectName("photoProto_comboBox")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.gridLayout_11.addWidget(self.photoProto_comboBox, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem10, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.photoWaitFrames_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.photoWaitFrames_spinBox.setObjectName("photoWaitFrames_spinBox")
        self.horizontalLayout_2.addWidget(self.photoWaitFrames_spinBox)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.gridLayout_11.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.testPhotoStimTrigger_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.testPhotoStimTrigger_pushButton.setObjectName("testPhotoStimTrigger_pushButton")
        self.gridLayout_11.addWidget(self.testPhotoStimTrigger_pushButton, 2, 2, 1, 1)
        self.powerDaqDevice_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerDaqDevice_lineEdit.sizePolicy().hasHeightForWidth())
        self.powerDaqDevice_lineEdit.setSizePolicy(sizePolicy)
        self.powerDaqDevice_lineEdit.setMaxLength(500)
        self.powerDaqDevice_lineEdit.setObjectName("powerDaqDevice_lineEdit")
        self.gridLayout_11.addWidget(self.powerDaqDevice_lineEdit, 3, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 4, 0, 1, 1)
        self.testPower_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.testPower_pushButton.setObjectName("testPower_pushButton")
        self.gridLayout_11.addWidget(self.testPower_pushButton, 3, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.photoDuration_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.photoDuration_spinBox.setMaximum(10000)
        self.photoDuration_spinBox.setProperty("value", 150)
        self.photoDuration_spinBox.setObjectName("photoDuration_spinBox")
        self.horizontalLayout_9.addWidget(self.photoDuration_spinBox)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.gridLayout_11.addLayout(self.horizontalLayout_9, 4, 2, 1, 1)
        self.SendPowerVolt_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.SendPowerVolt_checkBox.setObjectName("SendPowerVolt_checkBox")
        self.gridLayout_11.addWidget(self.SendPowerVolt_checkBox, 0, 2, 1, 1)
        self.run_groupBox = QtWidgets.QGroupBox(self.tab)
        self.run_groupBox.setGeometry(QtCore.QRect(900, 520, 331, 51))
        self.run_groupBox.setTitle("")
        self.run_groupBox.setObjectName("run_groupBox")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.run_groupBox)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 311, 31))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.reset_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_pushButton.setSizePolicy(sizePolicy)
        self.reset_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reset_pushButton.setFont(font)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.gridLayout_10.addWidget(self.reset_pushButton, 0, 3, 1, 1)
        self.run_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_pushButton.sizePolicy().hasHeightForWidth())
        self.run_pushButton.setSizePolicy(sizePolicy)
        self.run_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.run_pushButton.setFont(font)
        self.run_pushButton.setObjectName("run_pushButton")
        self.gridLayout_10.addWidget(self.run_pushButton, 0, 0, 1, 1)
        self.stop_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_pushButton.sizePolicy().hasHeightForWidth())
        self.stop_pushButton.setSizePolicy(sizePolicy)
        self.stop_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.gridLayout_10.addWidget(self.stop_pushButton, 0, 1, 1, 1)
        self.test_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_pushButton.sizePolicy().hasHeightForWidth())
        self.test_pushButton.setSizePolicy(sizePolicy)
        self.test_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.test_pushButton.setObjectName("test_pushButton")
        self.gridLayout_10.addWidget(self.test_pushButton, 0, 2, 1, 1)
        self.ImageWindow.raise_()
        self.Prairie_groupBox.raise_()
        self.OfflineAnalysis_groupBox.raise_()
        self.DisplayOptions_groupBox.raise_()
        self.StimOptions_groupBox.raise_()
        self.caiman_groupBox.raise_()
        self.plotArea_graphicsLayoutWidget.raise_()
        self.Thresh_tableWidget.raise_()
        self.Blink_groupBox.raise_()
        self.gridLayoutWidget_8.raise_()
        self.groupBox.raise_()
        self.opsinMask_groupBox.raise_()
        self.config_groupBox.raise_()
        self.photostim_groupBox.raise_()
        self.run_groupBox.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(130, 0, 991, 761))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.plot_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.plot_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.plot_gridLayout.setObjectName("plot_gridLayout")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1628, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.currentZoom_comboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyRTAOI"))
        self.Prairie_groupBox.setTitle(_translate("MainWindow", "Prairie settings"))
        self.currentZoom_comboBox.setCurrentText(_translate("MainWindow", "2"))
        self.currentZoom_comboBox.setItemText(0, _translate("MainWindow", "1.14"))
        self.currentZoom_comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.currentZoom_comboBox.setItemText(2, _translate("MainWindow", "4"))
        self.currentZoom_comboBox.setItemText(3, _translate("MainWindow", "8"))
        self.currentZoom_comboBox.setItemText(4, _translate("MainWindow", "16"))
        self.label_13.setText(_translate("MainWindow", "Buffered frames"))
        self.label_12.setText(_translate("MainWindow", "Flip rows"))
        self.flipRow_comboBox.setItemText(0, _translate("MainWindow", "Even"))
        self.flipRow_comboBox.setItemText(1, _translate("MainWindow", "Odd"))
        self.label_24.setText(_translate("MainWindow", "Current zoom"))
        self.connectPV_pushButton.setText(_translate("MainWindow", "Connect Prairie"))
        self.OfflineAnalysis_groupBox.setTitle(_translate("MainWindow", "Offline analysis"))
        self.moviePath_lineEdit.setText(_translate("MainWindow", "U:/simulate_movie/20170823.tif"))
        self.loadMoviePath_pushButton.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Movie Path"))
        self.IsOffline_radioButton.setText(_translate("MainWindow", "Run Offline"))
        self.DisplayOptions_groupBox.setTitle(_translate("MainWindow", "Display settings"))
        self.plotSTAonMasks_pushButton.setText(_translate("MainWindow", "Show STA on ROIs"))
        self.plotSTA_pushButton.setText(_translate("MainWindow", "Plot STA traces"))
        self.showComponents_pushButton.setText(_translate("MainWindow", "Show ROIs"))
        self.denoiseOn_checkBox.setText(_translate("MainWindow", "Denoise"))
        self.displayOn_checkBox.setText(_translate("MainWindow", "Display On"))
        self.plotOn_checkBox.setText(_translate("MainWindow", "Plot On"))
        self.showFOV_pushButton.setText(_translate("MainWindow", "Show FOV"))
        self.label_16.setText(_translate("MainWindow", " Plot every "))
        self.label_17.setText(_translate("MainWindow", " frames"))
        self.StimOptions_groupBox.setTitle(_translate("MainWindow", "Stimulation settings"))
        self.label_19.setText(_translate("MainWindow", "Dev/Ch"))
        self.label_8.setText(_translate("MainWindow", "Inter stim interval"))
        self.label_9.setText(_translate("MainWindow", "Numer of stims"))
        self.label_10.setText(_translate("MainWindow", "Pre frame"))
        self.label_11.setText(_translate("MainWindow", "Post frame"))
        self.label_6.setText(_translate("MainWindow", "Start frame"))
        self.label_14.setText(_translate("MainWindow", "Avg start"))
        self.label_15.setText(_translate("MainWindow", "Avg stop"))
        self.stimDaqDevice_lineEdit.setText(_translate("MainWindow", "Dev9/ao0"))
        self.testTTLTrigger_pushButton.setText(_translate("MainWindow", "Reset/Test"))
        self.enableStimTrigger_checkBox.setText(_translate("MainWindow", "Enable TTL"))
        self.caiman_groupBox.setTitle(_translate("MainWindow", "Caiman initialisation"))
        self.initialise_pushButton.setText(_translate("MainWindow", "Initialise"))
        self.refMoviePath_lineEdit.setText(_translate("MainWindow", "U:/simulate_movie/20170823.tif"))
        self.label_4.setText(_translate("MainWindow", "Reference Path"))
        self.UseOpsinMask_radioButton.setText(_translate("MainWindow", "C1V1"))
        self.label_5.setText(_translate("MainWindow", "Init num ROIs"))
        self.loadMask_pushButton.setText(_translate("MainWindow", "Load mask"))
        self.label_3.setText(_translate("MainWindow", "Max num ROIs"))
        self.label_7.setText(_translate("MainWindow", "Downsampling"))
        self.UseOnacidMask_radioButton.setText(_translate("MainWindow", "From file"))
        self.UseONACID_checkBox.setText(_translate("MainWindow", "Enable ONACID"))
        self.loadRefMoviePath_pushButton.setText(_translate("MainWindow", "Browse"))
        self.takeRefMovie_pushButton.setText(_translate("MainWindow", "Take Ref Movie"))
        self.Blink_groupBox.setTitle(_translate("MainWindow", "Blink settings"))
        self.selectAll_checkBox.setText(_translate("MainWindow", "select all"))
        self.clearTargets_pushButton.setText(_translate("MainWindow", "Clear all"))
        self.connectBlink_pushButton.setText(_translate("MainWindow", "Connect Blink"))
        self.SendCoords_pushButton.setText(_translate("MainWindow", "Send Coords"))
        self.addNewROIsToTarget_checkBox.setText(_translate("MainWindow", "auto add"))
        self.updateTargets_pushButton.setText(_translate("MainWindow", "Update targets"))
        self.label_20.setText(_translate("MainWindow", "y ="))
        self.CurrentFrameIdx_label.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", " x ="))
        self.label_2.setText(_translate("MainWindow", " Current Frame:"))
        self.removeMode_pushButton.setText(_translate("MainWindow", "Start remove"))
        self.groupBox.setTitle(_translate("MainWindow", "Save results"))
        self.label_25.setText(_translate("MainWindow", "Save Path"))
        self.browseResultPath_pushButton.setText(_translate("MainWindow", "Browse"))
        self.getPathFromPV_pushButton.setText(_translate("MainWindow", "Get from Praire"))
        self.saveResult_pushButton.setText(_translate("MainWindow", "Save results"))
        self.opsinMask_groupBox.setTitle(_translate("MainWindow", "C1V1 mask"))
        self.label_26.setText(_translate("MainWindow", "Image Path"))
        self.loadOpsinImgPath_pushButton.setText(_translate("MainWindow", "Browse"))
        self.opsinImgPath_lineEdit.setText(_translate("MainWindow", "U:/simulate_movie/20170823_Ch01.tif"))
        self.label_27.setText(_translate("MainWindow", "Min area"))
        self.label_29.setText(_translate("MainWindow", "Cell radius"))
        self.label_28.setText(_translate("MainWindow", "Overlap"))
        self.createMask_pushButton.setText(_translate("MainWindow", "Create mask"))
        self.showCellsOnMask_pushButton.setText(_translate("MainWindow", "Show cells on mask"))
        self.config_groupBox.setTitle(_translate("MainWindow", "Config"))
        self.saveConfig_pushButton.setText(_translate("MainWindow", "Save configuration"))
        self.loadConfig_pushButton.setText(_translate("MainWindow", "Load configuration"))
        self.photostim_groupBox.setTitle(_translate("MainWindow", "Photostim options"))
        self.label_31.setText(_translate("MainWindow", "Duration (ms)"))
        self.photostimDaqDevice_lineEdit.setText(_translate("MainWindow", "Dev9/ao1"))
        self.label_22.setText(_translate("MainWindow", "Wait frames"))
        self.label_21.setText(_translate("MainWindow", "Trigger on:"))
        self.label_23.setText(_translate("MainWindow", "Trigger Dev/Ch"))
        self.photoProto_comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.photoProto_comboBox.setItemText(1, _translate("MainWindow", "Fix frames"))
        self.photoProto_comboBox.setItemText(2, _translate("MainWindow", "Above threshold"))
        self.photoProto_comboBox.setItemText(3, _translate("MainWindow", "Below threshold"))
        self.photoProto_comboBox.setItemText(4, _translate("MainWindow", "Upon detection"))
        self.testPhotoStimTrigger_pushButton.setText(_translate("MainWindow", "Reset/Test"))
        self.powerDaqDevice_lineEdit.setText(_translate("MainWindow", "Dev9/ao0"))
        self.label_32.setText(_translate("MainWindow", "Power Dev/Ch"))
        self.label_33.setText(_translate("MainWindow", "Power/cell (mW)"))
        self.testPower_pushButton.setText(_translate("MainWindow", "Reset/Test"))
        self.SendPowerVolt_checkBox.setText(_translate("MainWindow", "Control power"))
        self.reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.run_pushButton.setText(_translate("MainWindow", "Run"))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.test_pushButton.setText(_translate("MainWindow", "Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Plot"))

from pyqtgraph import GraphicsLayoutWidget
