# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1213, 915)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1211, 891))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ImageWindow = GraphicsLayoutWidget(self.tab)
        self.ImageWindow.setGeometry(QtCore.QRect(30, 30, 512, 512))
        self.ImageWindow.setMouseTracking(True)
        self.ImageWindow.setLineWidth(0)
        self.ImageWindow.setObjectName("ImageWindow")
        self.Prairie_groupBox = QtWidgets.QGroupBox(self.tab)
        self.Prairie_groupBox.setGeometry(QtCore.QRect(550, -1, 341, 111))
        self.Prairie_groupBox.setObjectName("Prairie_groupBox")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.Prairie_groupBox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 321, 81))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.connectPV_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.connectPV_pushButton.setObjectName("connectPV_pushButton")
        self.gridLayout_5.addWidget(self.connectPV_pushButton, 0, 3, 1, 1)
        self.pvBufferFrames_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.pvBufferFrames_spinBox.setMinimum(1)
        self.pvBufferFrames_spinBox.setMaximum(30)
        self.pvBufferFrames_spinBox.setProperty("value", 1)
        self.pvBufferFrames_spinBox.setObjectName("pvBufferFrames_spinBox")
        self.gridLayout_5.addWidget(self.pvBufferFrames_spinBox, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.flipRow_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.flipRow_comboBox.setObjectName("flipRow_comboBox")
        self.flipRow_comboBox.addItem("")
        self.flipRow_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.flipRow_comboBox, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 0, 1, 1)
        self.currentZoom_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.currentZoom_comboBox.setObjectName("currentZoom_comboBox")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.currentZoom_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.currentZoom_comboBox, 2, 1, 1, 1)
        self.OfflineAnalysis_groupBox = QtWidgets.QGroupBox(self.tab)
        self.OfflineAnalysis_groupBox.setGeometry(QtCore.QRect(550, 450, 341, 91))
        self.OfflineAnalysis_groupBox.setObjectName("OfflineAnalysis_groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.OfflineAnalysis_groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 321, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.moviePath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.moviePath_lineEdit.setObjectName("moviePath_lineEdit")
        self.gridLayout_4.addWidget(self.moviePath_lineEdit, 1, 1, 1, 1)
        self.loadMoviePath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.loadMoviePath_pushButton.setObjectName("loadMoviePath_pushButton")
        self.gridLayout_4.addWidget(self.loadMoviePath_pushButton, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.IsOffline_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.IsOffline_radioButton.setObjectName("IsOffline_radioButton")
        self.gridLayout_4.addWidget(self.IsOffline_radioButton, 0, 0, 1, 1)
        self.DisplayOptions_groupBox = QtWidgets.QGroupBox(self.tab)
        self.DisplayOptions_groupBox.setGeometry(QtCore.QRect(900, 120, 261, 141))
        self.DisplayOptions_groupBox.setObjectName("DisplayOptions_groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.DisplayOptions_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.denoiseOn_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.denoiseOn_checkBox.setChecked(True)
        self.denoiseOn_checkBox.setObjectName("denoiseOn_checkBox")
        self.verticalLayout_2.addWidget(self.denoiseOn_checkBox)
        self.displayOn_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.displayOn_checkBox.setChecked(True)
        self.displayOn_checkBox.setObjectName("displayOn_checkBox")
        self.verticalLayout_2.addWidget(self.displayOn_checkBox)
        self.plotOn_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.plotOn_checkBox.setChecked(True)
        self.plotOn_checkBox.setObjectName("plotOn_checkBox")
        self.verticalLayout_2.addWidget(self.plotOn_checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_8.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refreshFrame_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.refreshFrame_spinBox.setMinimum(1)
        self.refreshFrame_spinBox.setMaximum(9000)
        self.refreshFrame_spinBox.setProperty("value", 30)
        self.refreshFrame_spinBox.setDisplayIntegerBase(10)
        self.refreshFrame_spinBox.setObjectName("refreshFrame_spinBox")
        self.horizontalLayout.addWidget(self.refreshFrame_spinBox)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.gridLayout_8.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 1, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plotSTA_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotSTA_pushButton.sizePolicy().hasHeightForWidth())
        self.plotSTA_pushButton.setSizePolicy(sizePolicy)
        self.plotSTA_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.plotSTA_pushButton.setObjectName("plotSTA_pushButton")
        self.gridLayout_7.addWidget(self.plotSTA_pushButton, 3, 0, 1, 1)
        self.showComponents_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showComponents_pushButton.setObjectName("showComponents_pushButton")
        self.gridLayout_7.addWidget(self.showComponents_pushButton, 0, 0, 1, 1)
        self.plotSTAonMasks_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.plotSTAonMasks_pushButton.setObjectName("plotSTAonMasks_pushButton")
        self.gridLayout_7.addWidget(self.plotSTAonMasks_pushButton, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 4, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.StimOptiions_groupBox = QtWidgets.QGroupBox(self.tab)
        self.StimOptiions_groupBox.setGeometry(QtCore.QRect(550, 270, 341, 171))
        self.StimOptiions_groupBox.setObjectName("StimOptiions_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.StimOptiions_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 11, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 2, 1, 1)
        self.stimStartFrame_spinBox = QtWidgets.QSpinBox(self.StimOptiions_groupBox)
        self.stimStartFrame_spinBox.setMinimum(1)
        self.stimStartFrame_spinBox.setMaximum(9000)
        self.stimStartFrame_spinBox.setProperty("value", 238)
        self.stimStartFrame_spinBox.setObjectName("stimStartFrame_spinBox")
        self.gridLayout.addWidget(self.stimStartFrame_spinBox, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.interStimInterval_spinBox = QtWidgets.QSpinBox(self.StimOptiions_groupBox)
        self.interStimInterval_spinBox.setMinimum(1)
        self.interStimInterval_spinBox.setMaximum(9000)
        self.interStimInterval_spinBox.setProperty("value", 310)
        self.interStimInterval_spinBox.setObjectName("interStimInterval_spinBox")
        self.gridLayout.addWidget(self.interStimInterval_spinBox, 7, 1, 1, 1)
        self.staPreFrame_spinBox = QtWidgets.QSpinBox(self.StimOptiions_groupBox)
        self.staPreFrame_spinBox.setMinimum(1)
        self.staPreFrame_spinBox.setMaximum(900)
        self.staPreFrame_spinBox.setProperty("value", 60)
        self.staPreFrame_spinBox.setObjectName("staPreFrame_spinBox")
        self.gridLayout.addWidget(self.staPreFrame_spinBox, 2, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 8, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.StimOptiions_groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 2, 1, 1)
        self.staPostFrame_spinBox = QtWidgets.QSpinBox(self.StimOptiions_groupBox)
        self.staPostFrame_spinBox.setMinimum(1)
        self.staPostFrame_spinBox.setMaximum(9000)
        self.staPostFrame_spinBox.setProperty("value", 120)
        self.staPostFrame_spinBox.setObjectName("staPostFrame_spinBox")
        self.gridLayout.addWidget(self.staPostFrame_spinBox, 7, 5, 1, 1)
        self.numberStims_spinBox = QtWidgets.QSpinBox(self.StimOptiions_groupBox)
        self.numberStims_spinBox.setMinimum(1)
        self.numberStims_spinBox.setMaximum(500)
        self.numberStims_spinBox.setProperty("value", 15)
        self.numberStims_spinBox.setDisplayIntegerBase(10)
        self.numberStims_spinBox.setObjectName("numberStims_spinBox")
        self.gridLayout.addWidget(self.numberStims_spinBox, 8, 1, 1, 1)
        self.staAvgStartFrame_spinBox = QtWidgets.QSpinBox(self.StimOptiions_groupBox)
        self.staAvgStartFrame_spinBox.setMinimum(1)
        self.staAvgStartFrame_spinBox.setMaximum(300)
        self.staAvgStartFrame_spinBox.setProperty("value", 1)
        self.staAvgStartFrame_spinBox.setDisplayIntegerBase(10)
        self.staAvgStartFrame_spinBox.setObjectName("staAvgStartFrame_spinBox")
        self.gridLayout.addWidget(self.staAvgStartFrame_spinBox, 8, 5, 1, 1)
        self.staAvgStopFrame_spinBox = QtWidgets.QSpinBox(self.StimOptiions_groupBox)
        self.staAvgStopFrame_spinBox.setMinimum(1)
        self.staAvgStopFrame_spinBox.setMaximum(9000)
        self.staAvgStopFrame_spinBox.setProperty("value", 30)
        self.staAvgStopFrame_spinBox.setDisplayIntegerBase(10)
        self.staAvgStopFrame_spinBox.setObjectName("staAvgStopFrame_spinBox")
        self.gridLayout.addWidget(self.staAvgStopFrame_spinBox, 10, 5, 1, 1)
        self.stimDaqDevice_lineEdit = QtWidgets.QLineEdit(self.StimOptiions_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stimDaqDevice_lineEdit.sizePolicy().hasHeightForWidth())
        self.stimDaqDevice_lineEdit.setSizePolicy(sizePolicy)
        self.stimDaqDevice_lineEdit.setMaxLength(500)
        self.stimDaqDevice_lineEdit.setObjectName("stimDaqDevice_lineEdit")
        self.gridLayout.addWidget(self.stimDaqDevice_lineEdit, 11, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 8, 6, 1, 1)
        self.testTTLTrigger_pushButton = QtWidgets.QPushButton(self.StimOptiions_groupBox)
        self.testTTLTrigger_pushButton.setObjectName("testTTLTrigger_pushButton")
        self.gridLayout.addWidget(self.testTTLTrigger_pushButton, 11, 5, 1, 1)
        self.enableStimTrigger_checkBox = QtWidgets.QCheckBox(self.StimOptiions_groupBox)
        self.enableStimTrigger_checkBox.setObjectName("enableStimTrigger_checkBox")
        self.gridLayout.addWidget(self.enableStimTrigger_checkBox, 11, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.caiman_groupBox = QtWidgets.QGroupBox(self.tab)
        self.caiman_groupBox.setGeometry(QtCore.QRect(550, 120, 341, 141))
        self.caiman_groupBox.setObjectName("caiman_groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.caiman_groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 321, 74))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.UseONACID_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.UseONACID_checkBox.setObjectName("UseONACID_checkBox")
        self.gridLayout_2.addWidget(self.UseONACID_checkBox, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 4, 1, 1)
        self.InitNumROIs_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.InitNumROIs_spinBox.setMinimum(1)
        self.InitNumROIs_spinBox.setProperty("value", 3)
        self.InitNumROIs_spinBox.setObjectName("InitNumROIs_spinBox")
        self.gridLayout_2.addWidget(self.InitNumROIs_spinBox, 1, 3, 1, 1)
        self.dsFactor_SpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.dsFactor_SpinBox.setDecimals(2)
        self.dsFactor_SpinBox.setMinimum(1.0)
        self.dsFactor_SpinBox.setMaximum(15.0)
        self.dsFactor_SpinBox.setProperty("value", 1.5)
        self.dsFactor_SpinBox.setObjectName("dsFactor_SpinBox")
        self.gridLayout_2.addWidget(self.dsFactor_SpinBox, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        self.MaxNumROIs_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.MaxNumROIs_spinBox.setMinimum(1)
        self.MaxNumROIs_spinBox.setProperty("value", 30)
        self.MaxNumROIs_spinBox.setObjectName("MaxNumROIs_spinBox")
        self.gridLayout_2.addWidget(self.MaxNumROIs_spinBox, 3, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.caiman_groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 321, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.loadRefMoviePath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.loadRefMoviePath_pushButton.setObjectName("loadRefMoviePath_pushButton")
        self.gridLayout_3.addWidget(self.loadRefMoviePath_pushButton, 0, 3, 1, 1)
        self.refMoviePath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.refMoviePath_lineEdit.setObjectName("refMoviePath_lineEdit")
        self.gridLayout_3.addWidget(self.refMoviePath_lineEdit, 0, 1, 1, 2)
        self.plotArea_graphicsLayoutWidget = GraphicsLayoutWidget(self.tab)
        self.plotArea_graphicsLayoutWidget.setGeometry(QtCore.QRect(30, 670, 651, 171))
        self.plotArea_graphicsLayoutWidget.setObjectName("plotArea_graphicsLayoutWidget")
        self.Thresh_tableWidget = QtWidgets.QTableWidget(self.tab)
        self.Thresh_tableWidget.setGeometry(QtCore.QRect(700, 670, 461, 171))
        self.Thresh_tableWidget.setShowGrid(True)
        self.Thresh_tableWidget.setCornerButtonEnabled(False)
        self.Thresh_tableWidget.setObjectName("Thresh_tableWidget")
        self.Thresh_tableWidget.setColumnCount(0)
        self.Thresh_tableWidget.setRowCount(0)
        self.Thresh_tableWidget.horizontalHeader().setVisible(True)
        self.Thresh_tableWidget.horizontalHeader().setHighlightSections(False)
        self.Thresh_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.Blink_groupBox = QtWidgets.QGroupBox(self.tab)
        self.Blink_groupBox.setGeometry(QtCore.QRect(900, -1, 261, 111))
        self.Blink_groupBox.setObjectName("Blink_groupBox")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.Blink_groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 245, 81))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.selectAll_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.selectAll_checkBox.setObjectName("selectAll_checkBox")
        self.gridLayout_6.addWidget(self.selectAll_checkBox, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 2, 1, 1, 1)
        self.clearTargets_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.clearTargets_pushButton.setObjectName("clearTargets_pushButton")
        self.gridLayout_6.addWidget(self.clearTargets_pushButton, 1, 0, 1, 1)
        self.connectBlink_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.connectBlink_pushButton.setObjectName("connectBlink_pushButton")
        self.gridLayout_6.addWidget(self.connectBlink_pushButton, 0, 2, 1, 1)
        self.SendCoords_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.SendCoords_pushButton.setObjectName("SendCoords_pushButton")
        self.gridLayout_6.addWidget(self.SendCoords_pushButton, 1, 2, 1, 1)
        self.addNewROIsToTarget_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.addNewROIsToTarget_checkBox.setObjectName("addNewROIsToTarget_checkBox")
        self.gridLayout_6.addWidget(self.addNewROIsToTarget_checkBox, 0, 1, 1, 1)
        self.updateTargets_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.updateTargets_pushButton.setObjectName("updateTargets_pushButton")
        self.gridLayout_6.addWidget(self.updateTargets_pushButton, 1, 1, 1, 1)
        self.photostim_groupBox = QtWidgets.QGroupBox(self.tab)
        self.photostim_groupBox.setGeometry(QtCore.QRect(900, 270, 261, 171))
        self.photostim_groupBox.setObjectName("photostim_groupBox")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.photostim_groupBox)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 288, 141))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.photostimDaqDevice_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photostimDaqDevice_lineEdit.sizePolicy().hasHeightForWidth())
        self.photostimDaqDevice_lineEdit.setSizePolicy(sizePolicy)
        self.photostimDaqDevice_lineEdit.setMaxLength(500)
        self.photostimDaqDevice_lineEdit.setObjectName("photostimDaqDevice_lineEdit")
        self.horizontalLayout_3.addWidget(self.photostimDaqDevice_lineEdit)
        self.testPhotoStimTrigger_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.testPhotoStimTrigger_pushButton.setObjectName("testPhotoStimTrigger_pushButton")
        self.horizontalLayout_3.addWidget(self.testPhotoStimTrigger_pushButton)
        self.gridLayout_11.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 1, 0, 1, 1)
        self.photoProto_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_10)
        self.photoProto_comboBox.setObjectName("photoProto_comboBox")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.photoProto_comboBox.addItem("")
        self.gridLayout_11.addWidget(self.photoProto_comboBox, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem7, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.photoWaitFrames_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.photoWaitFrames_spinBox.setObjectName("photoWaitFrames_spinBox")
        self.horizontalLayout_2.addWidget(self.photoWaitFrames_spinBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.gridLayout_11.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(30, 560, 511, 22))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.xPos_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.xPos_label.setText("")
        self.xPos_label.setObjectName("xPos_label")
        self.gridLayout_9.addWidget(self.xPos_label, 0, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 3, 1, 1)
        self.CurrentFrameIdx_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.CurrentFrameIdx_label.setObjectName("CurrentFrameIdx_label")
        self.gridLayout_9.addWidget(self.CurrentFrameIdx_label, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 5, 1, 1)
        self.yPos_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.yPos_label.setText("")
        self.yPos_label.setObjectName("yPos_label")
        self.gridLayout_9.addWidget(self.yPos_label, 0, 6, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 0, 7, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(910, 590, 241, 61))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.run_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_pushButton.sizePolicy().hasHeightForWidth())
        self.run_pushButton.setSizePolicy(sizePolicy)
        self.run_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.run_pushButton.setFont(font)
        self.run_pushButton.setObjectName("run_pushButton")
        self.gridLayout_10.addWidget(self.run_pushButton, 1, 0, 1, 1)
        self.stop_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_pushButton.sizePolicy().hasHeightForWidth())
        self.stop_pushButton.setSizePolicy(sizePolicy)
        self.stop_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.gridLayout_10.addWidget(self.stop_pushButton, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem12, 3, 0, 1, 1)
        self.reset_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_pushButton.setSizePolicy(sizePolicy)
        self.reset_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reset_pushButton.setFont(font)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.gridLayout_10.addWidget(self.reset_pushButton, 3, 2, 1, 1)
        self.test_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_pushButton.sizePolicy().hasHeightForWidth())
        self.test_pushButton.setSizePolicy(sizePolicy)
        self.test_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.test_pushButton.setObjectName("test_pushButton")
        self.gridLayout_10.addWidget(self.test_pushButton, 1, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(560, 550, 321, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadConfig_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadConfig_pushButton.sizePolicy().hasHeightForWidth())
        self.loadConfig_pushButton.setSizePolicy(sizePolicy)
        self.loadConfig_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadConfig_pushButton.setObjectName("loadConfig_pushButton")
        self.horizontalLayout_4.addWidget(self.loadConfig_pushButton)
        self.saveConfig_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveConfig_pushButton.sizePolicy().hasHeightForWidth())
        self.saveConfig_pushButton.setSizePolicy(sizePolicy)
        self.saveConfig_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.saveConfig_pushButton.setObjectName("saveConfig_pushButton")
        self.horizontalLayout_4.addWidget(self.saveConfig_pushButton)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(900, 450, 261, 121))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 241, 91))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.browseResultPath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.browseResultPath_pushButton.setObjectName("browseResultPath_pushButton")
        self.horizontalLayout_5.addWidget(self.browseResultPath_pushButton)
        self.getPathFromPV_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.getPathFromPV_pushButton.setObjectName("getPathFromPV_pushButton")
        self.horizontalLayout_5.addWidget(self.getPathFromPV_pushButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.saveResult_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.saveResult_pushButton.setObjectName("saveResult_pushButton")
        self.gridLayout_12.addWidget(self.saveResult_pushButton, 3, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 0, 0, 1, 1)
        self.saveResultPath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.saveResultPath_lineEdit.setText("")
        self.saveResultPath_lineEdit.setObjectName("saveResultPath_lineEdit")
        self.gridLayout_13.addWidget(self.saveResultPath_lineEdit, 0, 1, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(130, 0, 991, 761))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.staPlot_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.staPlot_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.staPlot_gridLayout.setObjectName("staPlot_gridLayout")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1213, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyRTAOI"))
        self.Prairie_groupBox.setTitle(_translate("MainWindow", "Prairie settings"))
        self.connectPV_pushButton.setText(_translate("MainWindow", "Connect Prairie"))
        self.label_13.setText(_translate("MainWindow", "Buffered frames"))
        self.label_12.setText(_translate("MainWindow", "Flip rows"))
        self.flipRow_comboBox.setItemText(0, _translate("MainWindow", "Even"))
        self.flipRow_comboBox.setItemText(1, _translate("MainWindow", "Odd"))
        self.label_24.setText(_translate("MainWindow", "Current zoom"))
        self.currentZoom_comboBox.setItemText(0, _translate("MainWindow", "1.14"))
        self.currentZoom_comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.currentZoom_comboBox.setItemText(2, _translate("MainWindow", "4"))
        self.currentZoom_comboBox.setItemText(3, _translate("MainWindow", "8"))
        self.currentZoom_comboBox.setItemText(4, _translate("MainWindow", "16"))
        self.OfflineAnalysis_groupBox.setTitle(_translate("MainWindow", "Offline analysis"))
        self.moviePath_lineEdit.setText(_translate("MainWindow", "U:/simulate_movie/20170823.tif"))
        self.loadMoviePath_pushButton.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Movie Path"))
        self.IsOffline_radioButton.setText(_translate("MainWindow", "Run Offline"))
        self.DisplayOptions_groupBox.setTitle(_translate("MainWindow", "Display options"))
        self.denoiseOn_checkBox.setText(_translate("MainWindow", "Denoise"))
        self.displayOn_checkBox.setText(_translate("MainWindow", "Display On"))
        self.plotOn_checkBox.setText(_translate("MainWindow", "Plot On"))
        self.label_17.setText(_translate("MainWindow", " frames"))
        self.label_16.setText(_translate("MainWindow", " Plot every "))
        self.plotSTA_pushButton.setText(_translate("MainWindow", "Plot STA traces"))
        self.showComponents_pushButton.setText(_translate("MainWindow", "Show ROIs"))
        self.plotSTAonMasks_pushButton.setText(_translate("MainWindow", "Show STA on ROIs"))
        self.StimOptiions_groupBox.setTitle(_translate("MainWindow", "Stimulation options"))
        self.label_19.setText(_translate("MainWindow", "Dev/Ch"))
        self.label_8.setText(_translate("MainWindow", "Inter stim interval"))
        self.label_9.setText(_translate("MainWindow", "Numer of stims"))
        self.label_10.setText(_translate("MainWindow", "Pre frame"))
        self.label_11.setText(_translate("MainWindow", "Post frame"))
        self.label_6.setText(_translate("MainWindow", "Start frame"))
        self.label_14.setText(_translate("MainWindow", "Avg start"))
        self.label_15.setText(_translate("MainWindow", "Avg stop"))
        self.stimDaqDevice_lineEdit.setText(_translate("MainWindow", "Dev9/ao0"))
        self.testTTLTrigger_pushButton.setText(_translate("MainWindow", "Reset/Test"))
        self.enableStimTrigger_checkBox.setText(_translate("MainWindow", "Enable TTL"))
        self.caiman_groupBox.setTitle(_translate("MainWindow", "CaImAn options"))
        self.label_3.setText(_translate("MainWindow", "Max num ROIs"))
        self.label_5.setText(_translate("MainWindow", "Init num ROIs"))
        self.UseONACID_checkBox.setText(_translate("MainWindow", "Enable ONACID"))
        self.label_7.setText(_translate("MainWindow", "Downsampling"))
        self.label_4.setText(_translate("MainWindow", "Reference Path"))
        self.loadRefMoviePath_pushButton.setText(_translate("MainWindow", "Browse"))
        self.refMoviePath_lineEdit.setText(_translate("MainWindow", "U:/simulate_movie/20170823.tif"))
        self.Blink_groupBox.setTitle(_translate("MainWindow", "Blink settings"))
        self.selectAll_checkBox.setText(_translate("MainWindow", "select all"))
        self.clearTargets_pushButton.setText(_translate("MainWindow", "Clear all"))
        self.connectBlink_pushButton.setText(_translate("MainWindow", "Connect Blink"))
        self.SendCoords_pushButton.setText(_translate("MainWindow", "Send Coords"))
        self.addNewROIsToTarget_checkBox.setText(_translate("MainWindow", "auto add"))
        self.updateTargets_pushButton.setText(_translate("MainWindow", "Update targets"))
        self.photostim_groupBox.setTitle(_translate("MainWindow", "Photostim options"))
        self.photostimDaqDevice_lineEdit.setText(_translate("MainWindow", "Dev9/ao1"))
        self.testPhotoStimTrigger_pushButton.setText(_translate("MainWindow", "Reset/Test"))
        self.label_23.setText(_translate("MainWindow", "Dev/Ch"))
        self.label_22.setText(_translate("MainWindow", "Wait frames"))
        self.photoProto_comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.photoProto_comboBox.setItemText(1, _translate("MainWindow", "Fix frames"))
        self.photoProto_comboBox.setItemText(2, _translate("MainWindow", "Above threshold"))
        self.photoProto_comboBox.setItemText(3, _translate("MainWindow", "Below threshold"))
        self.photoProto_comboBox.setItemText(4, _translate("MainWindow", "Upon detection"))
        self.label_21.setText(_translate("MainWindow", "Trigger on:"))
        self.label_18.setText(_translate("MainWindow", "                                                                                     x ="))
        self.CurrentFrameIdx_label.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", " Current Frame:"))
        self.label_20.setText(_translate("MainWindow", "y ="))
        self.run_pushButton.setText(_translate("MainWindow", "Run"))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.test_pushButton.setText(_translate("MainWindow", "Test"))
        self.loadConfig_pushButton.setText(_translate("MainWindow", "Load configuration"))
        self.saveConfig_pushButton.setText(_translate("MainWindow", "Save configuration"))
        self.groupBox.setTitle(_translate("MainWindow", "Save results"))
        self.browseResultPath_pushButton.setText(_translate("MainWindow", "Browse"))
        self.getPathFromPV_pushButton.setText(_translate("MainWindow", "Get from Praire"))
        self.saveResult_pushButton.setText(_translate("MainWindow", "Save results"))
        self.label_25.setText(_translate("MainWindow", "Save Path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Plot"))

from pyqtgraph import GraphicsLayoutWidget
